server:
  port: 7001
security:
  basic:
    enabled: true   # 启用安全认证处理
  user:
    name: edmin     # 用户名
    password: mldnjava  # 密码
spring:
  application:
    name: cnbicloud-server
  cloud:
    config:
      uri: http://cnbicloud-config:7101
      fail-fast: true
      password: mldnjava
      username: admin     
eureka: 
  client: # 客户端进行Eureka注册的配置,此台eureka服务在别的机子上进行注册
    service-url:
      defaultZone: http://edmin:mldnjava@192.168.1.118:7001/eureka
    register-with-eureka: false    # 当前的微服务不注册到eureka之中
    fetch-registry: false     # 不通过eureka获取注册信息
  instance: # eureak实例定义
    hostname: eureka118-7001.com # 定义Eureka实例所在的主机名称
    prefer-ip-address: true