server:
  port: 9501

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000


zuul:
  AuthorizedRequestFilter: 
    pre: 
      disable: false
  prefix: /cnbi-proxy
  ignored-services:
    "*"
  routes: 
    #cnbicloud-provider-company: /company-proxy/** 
    cnbicloud-provider-dept: /dept-proxy/**
    #cnbicloud-provider-upload: /upload-proxy/**
    
# zuul代理的安全认证
security:
  basic:
    enabled: true
  user:
    name: zdmin
    password: mldnjava

eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://edmin:mldnjava@eureka-7001.com:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
    instance-id: gateway-9501.com  # 在信息列表时显示主机名称
    prefer-ip-address: true     # 访问的路径变为IP地址

info:
  app.name: com-cnbicloud
  company.name: www.mldn.cn
  build.artifactId: $project.artifactId$
  build.version: $project.version$

spring:
  application:
    name: cnbicloud-zuul-gateway
