# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# http://blog.csdn.net/yuchao2015/article/details/52588407
# http://ms.csdn.net/geek/51618    weixin login
#https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419316505&token=189035bc71bb8c97fb0f468c938a89020ed8a3b2&lang=zh_CN
# ===================================================================    
spring:
    application:
        name: socketService
mina: 
    port: 8889 
    read-buffer-size: 209715209
    receive-buffer-size: 209715209 
    session-idle-time: 60
    interval: 60
    heartTimeout: 120
    start: 1  