spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev
  eureka-zone: http://edmin:mldnjava@192.168.1.118:7001/eureka,http://edmin:mldnjava@192.168.1.108:7001/eureka
  application:
    name: cnbiconfig-abc-dev
