spring:
  profiles:
    active:
    - dev	
---
security:
    basic:
        enabled: false
server:
 # context-path: /sec
  port: 82
spring:
    profiles: dev 
    application:
        name: cnbicloud-provider-user
    thymeleaf: 
        mode: HTML5
        encoding: UTF-8
        content-type: text/html; charset=utf-8
        cache: false   
    datasource: 
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.1.108:3306/security_api2
        username: root
        password: 1
        #platform: all
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
    redis:
      host: 192.168.1.120
      port: 6379
      password: 123456
      timeout: 1000
      database: 0
      pool:
        max-active: 10
        max-idle: 8
        min-idle: 2
        max-wait: 100   
    jpa:
        open-in-view: false
        #database-platform: org.hibernate.dialect.MySQLInnoDBDialect
        database: MYSQL
        show-sql: true
        generate-ddl: true
        properties: 
             ##hibernate.dialect: org.hibernate.dialect.MySQLInnoDBDialect
             hibernate.cache.use_second_level_cache: false
             hibernate.cache.use_query_cache: false
             hibernate.generate_statistics: false
             hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
        hibernate:
            ddl-auto: update
            naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
logging:
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG
eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://edmin:mldnjava@192.168.1.118:7001/eureka,http://edmin:mldnjava@192.168.1.108:7001/eureka
