server:
  port: 81


logging:
  level:
    com.cnbicloud.service: DEBUG

feign:
  compression:
    request:
      mime-types:       # 可以被压缩的类型
      - text/xml
      - application/xml
      - application/json
      min-request-size: 2048 # 超过2048的字节进行压缩


eureka: 
  client: 
    register-with-eureka: false #因为是消费都，也就是真正意义上的客户端,所以不用在euraka上注册 
    service-url: 
      defaultZone: http://edmin:mldnjava@192.168.1.108:7001/eureka